---
    - name: Installs haproxy load balancer
      apt: pkg=haproxy state=latest update_cache=yes
      
    - name: Pushes configuration 
      template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg mode=0640 owner=root group=root
      notify:   
        - restart haproxy
            