---
-hosts:web
- name: Configure Haproxy
  hosts: haproxy
  become: true
  tasks:
    - name: Installs haproxy load balancer
      apt: pkg=haproxy state=latest update_cache=yes
      
    - name: Pushes configuration 
      template: src=/home/devlikeops/work/ansible-apache2-haproxy/templates/haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg mode=0640 owner=root group=root
      notify:   
        - restart haproxy
            
  handlers:
        - name: restart haproxy
          service: name=haproxy state=restarted